galaxy_info:
  author: Josh Eisenbath
  description: Configure Supermicro BMC NetworkProtocols using Redfish APIs

  license: GPL-3.0-or-later

  min_ansible_version: '2.15'

  galaxy_tags: []

dependencies: []
