---
# defaults file for interfaces
interfaces_bmc_admin_user: "{{ bmc_admin_user }}"
interfaces_bmc_admin_password: "{{ bmc_admin_password }}"
interfaces_bmc_validate_certs: "{{ bmc_validate_certs }}"
interfaces_bmc_force_basic_auth: "{{ bmc_force_basic_auth }}"
interfaces_bmc_uri: "{{ bmc_uri }}"
...
