objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    ssm_host:
      description: Manages hosts in Supermicro Server Manager.
      name: ssm_host
      namespace: ''
      version_added: 1.2.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.2.0
